apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_DATA_ENGINE
          value: tsm1
        - name: INFLUXDB_GRAPHITE_0_BIND_ADDRESS
          value: :2003
        - name: INFLUXDB_GRAPHITE_0_DATABASE
          value: graphite
        - name: INFLUXDB_GRAPHITE_0_ENABLED
          value: "true"
        - name: INFLUXDB_GRAPHITE_BATCH_SIZE
          value: "1000"
        - name: INFLUXDB_GRAPHITE_PROTOCOL
          value: tcp
        - name: INFLUXDB_REPORTING_DISABLED
          value: "false"
        image: influxdb:latest
        imagePullPolicy: ""
        name: influxdb
        ports:
        - containerPort: 8083
        - containerPort: 8086
        - containerPort: 8090
        - containerPort: 2003
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: influxdb-claim0
        persistentVolumeClaim:
          claimName: influxdb-claim0
status: {}
